/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 helmet-optimized.glb 
Author: NotGabe (https://sketchfab.com/Not_Gabe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/daft-punk-helmet-thomas-bangalter-cbcea62f4655451cac60b979e6d556ec
Title: Daft Punk Helmet (Thomas Bangalter)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/helmet-optimized.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Chrome} position={[0, 0.029, 0.073]} scale={0.389} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.003']} position={[0, -0.14, 0.379]} rotation={[Math.PI / 2, 0, 0]} scale={[0.105, 0.121, 0.056]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Visor} position={[0, 0.007, 0.297]} scale={0.294} />
    </group>
  )
}

useGLTF.preload('/helmet-optimized.glb')
